### ISSUE TITLE
rc2 operator crashes

### ISSUE THREAD

**Issue by schubter** [appscode/voyager#1070]
upgraded the deployment from rc.1 to rc.2 and added the --haproxy-image-tag=1.8.8-7.0.0-rc.2-alpine param to the operator

there are two ingress' registered but the operator crashes when checking the first

<details>
 <summary>the crash log</summary>

```
I0523 07:43:37.093998       1 run.go:21] [Starting voyager...]
I0523 07:43:37.113848       1 http.go:97] [Running http server provider...]
I0523 07:43:38.320327       1 audit.go:229] No audit policy file provided for AdvancedAuditing, no events will be recorded.
I0523 07:43:38.355065       1 operator.go:107] [Ensuring CRD registration]
W0523 07:43:41.511949       1 servicemonitors.go:17] Skipping watching non-preferred GroupVersion:monitoring.coreos.com/v1 Kind:ServiceMonitor
I0523 07:43:41.513714       1 serve.go:96] Serving securely on [::]:8443
W0523 07:43:41.548495       1 validator.go:52] Checking ingress test/test-ing
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x10 pc=0x10bee89]
 goroutine 147 [running]:
github.com/appscode/voyager/apis/voyager/v1beta1.Ingress.IsValid(0xc4202c1058, 0x7, 0xc420296940, 0x1c, 0xc4202c1350, 0xc, 0x0, 0x0, 0xc4202c1369, 0x5, ...)
	/go/src/github.com/appscode/voyager/apis/voyager/v1beta1/validator.go:336 +0x5999
github.com/appscode/voyager/pkg/operator.(*Operator).ValidateIngress(0xc4203b3c00, 0x0, 0x0)
	/go/src/github.com/appscode/voyager/pkg/operator/validator.go:53 +0xb59
github.com/appscode/voyager/pkg/operator.(*Operator).Run(0xc4203b3c00, 0xc420054960)
	/go/src/github.com/appscode/voyager/pkg/operator/operator.go:167 +0x35
created by github.com/appscode/voyager/pkg/server.(*VoyagerServer).Run
	/go/src/github.com/appscode/voyager/pkg/server/server.go:58 +0x51
```
</details>

<details>
 <summary>the ingress in question</summary>

```yaml
kubectl describe ingress.voyager.appscode.com -n test test-ing
Name:         test-ing
Namespace:    cloud
Labels:       <none>
Annotations:  ingress.appscode.com/type=HostPort
              kubectl.kubernetes.io/last-applied-configuration={"apiVersion":"voyager.appscode.com/v1beta1","kind":"Ingress","metadata":{"annotations":{"ingress.appscode.com/type":"HostPort","kubernetes.io/ingress....
              kubernetes.io/ingress.class=voyager
API Version:  voyager.appscode.com/v1beta1
Kind:         Ingress
Metadata:
  Cluster Name:        
  Creation Timestamp:  2018-05-17T09:23:42Z
  Finalizers:
    voyager.appscode.com
  Generation:        1
  Resource Version:  1310104
  Self Link:         /apis/voyager.appscode.com/v1beta1/namespaces/test/ingresses/test-ing
  UID:               fd6f903e-59b3-11e8-933a-9600000a4865
Spec:
  Frontend Rules:
    Port:  80
    Rules:
      log-format %ci:%cp\ [%t]\ %ft\ %b/%s\ %Tq/%Tw/%Tc/%Tr/%Tt\ %ST\ %B\ %CC\ %CS\ %tsc\ %ac/%fc/%bc/%sc/%rc\ %sq/%bq\ %hr\ %hs\ {%[ssl_c_verify],%[ssl_fc_has_crt],%{+Q}[ssl_c_s_dn],%{+Q}[ssl_c_i_dn]}\ %{+Q}r
      http-request redirect prefix http://%[hdr(host),regsub(^www\.,,i)] code 301 if { hdr_beg(host) -i www. }
      http-request lua.auth-request oauth /auth/verify_token
      use_backend oauth if ! { var(txn.auth_response_successful) -m bool }
    Port:  443
    Rules:
      log-format %ci:%cp\ [%t]\ %ft\ %b/%s\ %Tq/%Tw/%Tc/%Tr/%Tt\ %ST\ %B\ %CC\ %CS\ %tsc\ %ac/%fc/%bc/%sc/%rc\ %sq/%bq\ %hr\ %hs\ {%[ssl_c_verify],%[ssl_fc_has_crt],%{+Q}[ssl_c_s_dn],%{+Q}[ssl_c_i_dn]}\ %{+Q}r
      http-request redirect prefix http://%[hdr(host),regsub(^www\.,,i)] code 301 if { hdr_beg(host) -i www. }
      rspadd Strict-Transport-Security:\ max-age=15768000;\ includeSubDomains;\ preload;
      http-request lua.auth-request oauth /auth/verify_token
      use_backend oauth if ! { var(txn.auth_response_successful) -m bool }
  Node Selector:
    Ingress:  test-voyager
  Rules:
    Host:  test.int
    Http:
      Alpn:
        h2
        http/1.1
        http/1.0
      Paths:
        Backend:
          Backend Rules:
            compression algo gzip
            compression type text/html text/plain text/css application/javascript
          Service Name:  api
          Service Port:  8080
    Host:                test.int
    Http:
      Alpn:
        h2
        http/1.1
        http/1.0
      Paths:
        Backend:
          Backend Rules:
            compression algo gzip
            compression type text/html text/plain text/css application/javascript
          Name:          oauth
          Service Name:  oauth
          Service Port:  8080
        Path:            /auth
  Tls:
    Hosts:
      test.int
    Secret Name:  tls-test
Events:
  Type    Reason                         Age   From              Message
  ----    ------                         ----  ----              -------
  Normal  DeploymentReconcileSuccessful  50m   voyager operator  Successfully patched HAProxy Deployment voyager-test-ing
  Normal  StatsServiceDeleteSuccessful   50m   voyager operator  Successfully deleted stats Service voyager-test-ing-stats
  Normal  DeploymentReconcileSuccessful  50m   voyager operator  Successfully patched HAProxy Deployment voyager-test-ing
  Normal  StatsServiceDeleteSuccessful   50m   voyager operator  Successfully deleted stats Service voyager-test-ing-stats
  Normal  DeploymentReconcileSuccessful  40m   voyager operator  Successfully patched HAProxy Deployment voyager-test-ing
  Normal  StatsServiceDeleteSuccessful   40m   voyager operator  Successfully deleted stats Service voyager-test-ing-stats
  Normal  DeploymentReconcileSuccessful  40m   voyager operator  Successfully patched HAProxy Deployment voyager-test-ing
  Normal  StatsServiceDeleteSuccessful   40m   voyager operator  Successfully deleted stats Service voyager-test-ing-stats
  Normal  DeploymentReconcileSuccessful  30m   voyager operator  Successfully patched HAProxy Deployment voyager-test-ing
  Normal  StatsServiceDeleteSuccessful   30m   voyager operator  Successfully deleted stats Service voyager-test-ing-stats
  Normal  DeploymentReconcileSuccessful  30m   voyager operator  Successfully patched HAProxy Deployment voyager-test-ing
  Normal  StatsServiceDeleteSuccessful   30m   voyager operator  Successfully deleted stats Service voyager-test-ing-stats
  Normal  StatsServiceDeleteSuccessful   20m   voyager operator  Successfully deleted stats Service voyager-test-ing-stats
  Normal  StatsServiceDeleteSuccessful   20m   voyager operator  Successfully deleted stats Service voyager-test-ing-stats
  Normal  DeploymentReconcileSuccessful  20m   voyager operator  Successfully patched HAProxy Deployment voyager-test-ing
  Normal  DeploymentReconcileSuccessful  20m   voyager operator  Successfully patched HAProxy Deployment voyager-test-ing
  Normal  DeploymentReconcileSuccessful  10m   voyager operator  Successfully patched HAProxy Deployment voyager-test-ing
  Normal  StatsServiceDeleteSuccessful   10m   voyager operator  Successfully deleted stats Service voyager-test-ing-stats
  Normal  DeploymentReconcileSuccessful  10m   voyager operator  Successfully patched HAProxy Deployment voyager-test-ing
  Normal  StatsServiceDeleteSuccessful   10m   voyager operator  Successfully deleted stats Service voyager-test-ing-stats
  Normal  DeploymentReconcileSuccessful  53s   voyager operator  Successfully patched HAProxy Deployment voyager-test-ing
  Normal  StatsServiceDeleteSuccessful   53s   voyager operator  Successfully deleted stats Service voyager-test-ing-stats
  Normal  DeploymentReconcileSuccessful  53s   voyager operator  Successfully patched HAProxy Deployment voyager-test-ing
  Normal  StatsServiceDeleteSuccessful   53s   voyager operator  Successfully deleted stats Service voyager-test-ing-stats
```
</details>

**Comment by tamalsaha** [comment]
oh! We are fixing it.

**Comment by tamalsaha** [comment]
Hi, try https://github.com/appscode/voyager/releases/tag/7.0.0-rc.3 . Should be fixed now.

**Comment by schubter** [comment]
Hey,

already on it, just waiting for the image to show up on the registry :)

thanks

**Comment by tamalsaha** [comment]
Pushed the image. Try now.

**Comment by schubter** [comment]
works like a charm, tyvm

**Comment by tamalsaha** [comment]
Thanks for all the help and support!
