### ISSUE TITLE
support of named servicePort

### ISSUE THREAD

**Issue by fentas** [appscode/voyager#1193]
_background:_ I am switching from `traefik` to `voyager` right now.

Up until now I used named `servicePort`'s within my ingress definitions like `http`.
But this will fail with
```sh
F0712 20:19:45.837924    1586 haproxy.go:58] [spec.rules[0].http.paths[0] is using invalid servicePort http for addr example.com:80 and path /. Reason: strconv.Atoi: parsing "http": invalid syntax]
goroutine 1 [running]:
github.com/appscode/voyager/vendor/github.com/golang/glog.stacks(0xc4205d2000, 0xc4206f63c0, 0xc1, 0x1d5)
	/go/src/github.com/appscode/voyager/vendor/github.com/golang/glog/glog.go:766 +0xcf
github.com/appscode/voyager/vendor/github.com/golang/glog.(*loggingT).output(0x41174e0, 0xc400000003, 0xc420684000, 0x3f0aec5, 0xa, 0x3a, 0x0)
	/go/src/github.com/appscode/voyager/vendor/github.com/golang/glog/glog.go:717 +0x322
github.com/appscode/voyager/vendor/github.com/golang/glog.(*loggingT).printDepth(0x41174e0, 0xc400000003, 0x1, 0xc420255b58, 0x1, 0x1)
	/go/src/github.com/appscode/voyager/vendor/github.com/golang/glog/glog.go:646 +0x12a
github.com/appscode/voyager/vendor/github.com/golang/glog.FatalDepth(0x1, 0xc420255b58, 0x1, 0x1)
	/go/src/github.com/appscode/voyager/vendor/github.com/golang/glog/glog.go:1131 +0x5d
github.com/appscode/voyager/vendor/github.com/appscode/go/log.Fatalln(0xc4207cac10, 0x1, 0x1)
	/go/src/github.com/appscode/voyager/vendor/github.com/appscode/go/log/log.go:21 +0xa8
github.com/appscode/voyager/pkg/cmds.NewCmdHAProxyController.func1(0xc42043d400, 0xc420600500, 0x0, 0xa)
	/go/src/github.com/appscode/voyager/pkg/cmds/haproxy.go:58 +0x231
github.com/appscode/voyager/vendor/github.com/spf13/cobra.(*Command).execute(0xc42043d400, 0xc4206003c0, 0xa, 0xa, 0xc42043d400, 0xc4206003c0)
	/go/src/github.com/appscode/voyager/vendor/github.com/spf13/cobra/command.go:766 +0x2c1
github.com/appscode/voyager/vendor/github.com/spf13/cobra.(*Command).ExecuteC(0xc42043cf00, 0xc42043db80, 0xc42043d900, 0xc42043d680)
	/go/src/github.com/appscode/voyager/vendor/github.com/spf13/cobra/command.go:852 +0x334
github.com/appscode/voyager/vendor/github.com/spf13/cobra.(*Command).Execute(0xc42043cf00, 0x5, 0xc42043cf00)
	/go/src/github.com/appscode/voyager/vendor/github.com/spf13/cobra/command.go:800 +0x2b
main.main()
	/go/src/github.com/appscode/voyager/main.go:16 +0x70
```

After changing it to the wanted port (`int`) it starts up.

**Comment by tamalsaha** [comment]
Can you show us the yaml that caused this issue?
