### ISSUE TITLE
Voyager stops with Fatal

### ISSUE THREAD

**Issue by endrec** [appscode/voyager#1471]
v12.0.0 ends with a Fatal when started:

```
F0103 10:48:09.218568       1 loadbalancer.go:174] <nil>
goroutine 1070 [running]:
github.com/golang/glog.stacks(0xc0007ab600, 0xc00008cb40, 0x39, 0x221)
	/src/vendor/github.com/golang/glog/glog.go:769 +0xb8
github.com/golang/glog.(*loggingT).output(0x4644e80, 0xc000000003, 0xc000346460, 0x4560295, 0xf, 0xae, 0x0)
	/src/vendor/github.com/golang/glog/glog.go:720 +0x372
github.com/golang/glog.(*loggingT).printDepth(0x4644e80, 0x3, 0x1, 0xc0012e5fb8, 0x1, 0x1)
	/src/vendor/github.com/golang/glog/glog.go:646 +0x129
github.com/golang/glog.FatalDepth(...)
	/src/vendor/github.com/golang/glog/glog.go:1134
github.com/appscode/go/log.Fatal(...)
	/src/vendor/github.com/appscode/go/log/log.go:17
github.com/appscode/voyager/pkg/ingress.(*loadBalancerController).Reconcile.func1(0xc00000e008)
	/src/pkg/ingress/loadbalancer.go:174 +0x92
created by github.com/appscode/voyager/pkg/ingress.(*loadBalancerController).Reconcile
	/src/pkg/ingress/loadbalancer.go:173 +0x39b
```

My first thought was that it's caused by some missing configuration somewhere, but it seems that `log.Fatal` is always called: https://github.com/appscode/voyager/blob/v12.0.0-rc.0/pkg/ingress/loadbalancer.go#L173

**Comment by tamalsaha** [comment]
Checking

**Comment by tamalsaha** [comment]
Fixed in https://github.com/appscode/voyager/releases/tag/v12.0.0-rc.1
